holos: match GitHub Actions workspace uid of 1001
So we can use the holos container in GitHub Actions.

Otherwise we get:

/usr/bin/docker exec  5f1de238265d91c890229e3fde9a69c5a6cf63e7cdac98152a1ab679840d3da2 sh -c "cat /etc/*release | grep ^ID"
node:fs:2367
    return binding.writeFileUtf8(
                   ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_7dbd0051-e549-4769-9b06-60fd0de18075'
    at Object.writeFileSync (node:fs:2367:20)
    at Object.appendFileSync (node:fs:2448:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v4/dist/index.js:3060:8)
    at Object.saveState (/__w/_actions/actions/checkout/v4/dist/index.js:2977:31)
    at 4866 (/__w/_actions/actions/checkout/v4/dist/index.js:2402:10)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v4/dist/index.js:38194:43)
    at 2565 (/__w/_actions/actions/checkout/v4/dist/index.js:150:34)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v4/dist/index.js:38194:43)
    at 9210 (/__w/_actions/actions/checkout/v4/dist/index.js:1171:36)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v4/dist/index.js:38194:43) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/__w/_temp/_runner_file_commands/save_state_7dbd0051-e549-4769-9b06-60fd0de18075'
}

Node.js v20.18.0